---

- hosts: all
  become: true
  tasks:

  - name: update repolistory index
    apt:
            update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    apt:
            name: apache2
            state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache
    apt:
            name: libapache2-mod-php
            state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repolistory index on RedHat
    dnf:
            update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install HTTPD package on RedHat
    dnf:
            name: httpd
            state: latest
    when: ansible_distribution == "CentOS"

  - name: add php support for RedHat
    dnf:
            name: php
            state: latest
    when: ansible_distribution == "CentOS"
