---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Centos)
    dnf:
            update_only: yes
            update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt:
            upgrade: dist
            update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 package & libapache2-mod-php
    apt:
            name: 
              - apache2
              - libapache2-mod-php
            state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install HTTPD & PHP  packages on CentOS
    dnf:
            name: 
              - httpd
              - php
            state: latest
    when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:
  
  - name: install MariaDB package (Centos)
    dnf:
            name: mariadb
            state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    apt:
            name: mariadb-server
            state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install Samba package
    package: 
      name: samba
      state: latest
